# Generated by Django 5.1 on 2025-02-24 00:03

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome comlpeto')),
                ('interesse', models.CharField(max_length=100, verbose_name='Area de interesse')),
                ('linkedin', models.CharField(max_length=100, verbose_name='Linkedin')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Membro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(default='1', verbose_name='team')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('deadline', models.DateField(null=True, verbose_name='Deadline')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Update')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('owner', models.OneToOneField(default=app.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='Slug')),
                ('focus', models.CharField(max_length=50, verbose_name='Focus')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('private', models.BooleanField(default=False)),
                ('invites', models.ManyToManyField(related_name='invited', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(default=app.models.CustomUser, related_name='participa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.team')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go', to='app.goal')),
            ],
        ),
    ]
