# Generated by Django 4.0.2 on 2022-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
