# Generated by Django 4.0.2 on 2022-02-26 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_membership_alter_team_participants_membership_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL), related_name='+', through='app.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
