# Generated by Django 4.0.2 on 2022-02-26 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_team_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invites',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='participants',
        ),
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
