# Generated by Django 4.0.2 on 2022-02-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_team_invites_alter_team_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
    ]
