# Generated by Django 4.0.2 on 2022-02-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_team_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='max',
        ),
    ]
