# Generated by Django 4.0.2 on 2022-02-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_team_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='invites',
        ),
    ]
