# Generated by Django 4.0.2 on 2022-02-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_membership_invites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='team',
        ),
        migrations.AddField(
            model_name='membership',
            name='a',
            field=models.CharField(default='', max_length=10),
        ),
    ]
