# Generated by Django 4.0.2 on 2022-02-26 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_team_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invites',
            field=models.ManyToManyField(related_name='invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
