# Generated by Django 4.0.2 on 2022-02-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_team_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('goal', models.CharField(max_length=200, verbose_name='Description')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.team')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go', to='app.goal')),
            ],
        ),
    ]
