# Generated by Django 4.0.2 on 2022-02-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_goal_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='team',
        ),
    ]
