# Generated by Django 4.0.2 on 2022-02-27 16:04

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_goal_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='team',
            field=models.OneToOneField(null=app.models.Team, on_delete=django.db.models.deletion.CASCADE, related_name='gooals', to='app.team'),
        ),
    ]
