# Generated by Django 4.0.2 on 2022-02-27 16:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_goal_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='team',
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ManyToManyField(null=app.models.Team, related_name='gooals', to='app.Team'),
            preserve_default=app.models.Team,
        ),
    ]
