# Generated by Django 4.0.2 on 2022-02-28 21:19

import app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_goal_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='team',
        ),
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ManyToManyField(default=app.models.CustomUser, related_name='gooals', to=settings.AUTH_USER_MODEL),
        ),
    ]
