# Generated by Django 4.0.2 on 2022-02-28 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_goal_team_goal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='owner',
            field=models.ManyToManyField(related_name='gooals', to=settings.AUTH_USER_MODEL),
        ),
    ]
