# Generated by Django 4.0.2 on 2022-02-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_goal_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='owner',
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.IntegerField(default='1', verbose_name='team'),
        ),
    ]
