# Generated by Django 5.1 on 2024-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_goal_goal_description_goal_deadline_goal_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='date_update',
            field=models.DateField(auto_now=True, null=True, verbose_name='Update'),
        ),
    ]
